### ISSUE TITLE
Saved call recordings location

### ISSUE THREAD

**Issue by mjain234** [jacopotediosi/GoogleDialerMod#11]
Hi there,
I want to know that where does the Google dialer mod saves it's recording files?

**Comment by jacopotediosi** [comment]
Hi and thanks for your question.
Firstly, _GoogleDialerMod_ doesn't save any recording files. GoogleDialerMod just allows you to enable and disable hidden features (including the call recording function) **that are already included** in the official Google Dialer app.
Then, the path where Google Dialer saves call recording audio files, accessible only with a file manager with root permissions, is `/data/data/com.google.android.dialer/files/callrecording/`.
I hope this helps.
