### ISSUE TITLE
empty recording

### ISSUE THREAD

**Issue by Electronic-Idiot** [jacopotediosi/GoogleDialerMod#12]
Mod made a recording button appear but when recorded file is played back,its completely silent
Realme x2 running pixel extended 4.0 (Android 12)

**Comment by uvmittal** [comment]
yep same with me in lavender(redmi note 7)
a12 evo6

**Comment by ezxpro** [comment]
Same here. Redmi 7, LineageOS 18.1, Android 11

**Comment by windscolorme** [comment]
> Mod made a recording button appear but when recorded file is played back,its completely silent Realme x2 running pixel extended 4.0 (Android 12)

https://t.me/RealmeX2Updates/485 Hi, you can try these roms which are based on Realme UI RUI 2.0, follow the guide in the group. These rom supports call recording such as https://github.com/chenxiaolong/BCR.

**Comment by Electronic-Idiot** [comment]
> > Mod made a recording button appear but when recorded file is played back,its completely silent Realme x2 running pixel extended 4.0 (Android 12)
> 
> https://t.me/RealmeX2Updates/485 Hi, you can try these roms which are based on Realme UI RUI 2.0, follow the guide in the group. These rom supports call recording such as https://github.com/chenxiaolong/BCR.

I totally forgot I opened this issue here,i am using OSS based ROM atm and recording is fine,btw are part of the custom rom scene of device....just curious
