### ISSUE TITLE
Not supported in your region problem

### ISSUE THREAD

**Issue by esakarya** [jacopotediosi/GoogleDialerMod#20]
after close phone app or restart phone.  phone setting call recording says Not supported in your region

**Comment by kunago** [comment]
When this happens, I enable and disable the location permission for the Google phone app. It then goes away. There seems to be another way Google phone uses to detect the location.

**Comment by esakarya** [comment]
After reatart 1 min later going work normally. Thats ok now but. i add some contacts to record all time list. But in first call not begin record automatically. Next call begin record

**Comment by kunago** [comment]
As for recording, it does and does not work every now and then but as was written somewhere else, it is more of an issue of Google phone, not this app. I would say it is 50:50 in my case.
