### ISSUE TITLE
Doesn't work on Galaxy S10

### ISSUE THREAD

**Issue by the4anoni** [jacopotediosi/GoogleDialerMod#24]
Hi
Like in topic, I tried both apk and magisk version on LineageOS 19 and Pixel experience 12.1. There are recording settings, but I can't record calls via google dialer.

**Comment by jacopotediosi** [comment]
Thanks for your reporting.

Please be more specific when you say something doesn't work.

Explain what steps you take, what error messages you get, what results you expect, and what results you get.

Also, try the latest release. If the problem persists, please reply to this issue and I will reopen it.

**Comment by the4anoni** [comment]
> Thanks for your reporting.
> 
> Please be more specific when you say something doesn't work.
> 
> Explain what steps you take, what error messages you get, what results you expect, and what results you get.
> 
> Also, try the latest release. If the problem persists, please reply to this issue and I will reopen it.

I was either getting error message "Not available in your country" or dialer didn't showed record option at all.

For now I am using AOSP Dialer.

**Comment by jacopotediosi** [comment]
> > Thanks for your reporting.
> > Please be more specific when you say something doesn't work.
> > Explain what steps you take, what error messages you get, what results you expect, and what results you get.
> > Also, try the latest release. If the problem persists, please reply to this issue and I will reopen it.
> 
> I was either getting error message "Not available in your country" or dialer didn't showed record option at all.
> 
> For now I am using AOSP Dialer.

Thank you for your clarification.
I know this project has been inactive for quite some time, but I have decided to take care of it again and maybe there will be more updates in the coming times.
In the meantime I have fixed the problems regarding storage access limitations on Android >= 11 that could cause bugs like the one you described in this issue.
If you want, please give a try to [version 1.04](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.04).
