### ISSUE TITLE
no sound in recording

### ISSUE THREAD

**Issue by sokolblyat9** [jacopotediosi/GoogleDialerMod#30]
after recording the call, I would like to listen to it, but no one can be heard in the recorded call, absolute silence.  I use redmi note 7, firmware arrow os 12.1

**Comment by jacopotediosi** [comment]
Thanks for your reporting.

GoogleDialerMod cannot modify Google Dialer source codes.
Its purpose is only to enable hidden features.
If the call recording button appears, GoogleDialerMod is doing its job.

To report Google Dialer bugs, such as the one reported in this issue, please contact Google.
