### ISSUE TITLE
Hang up the phone, no record saved 

### ISSUE THREAD

**Issue by History-exe** [jacopotediosi/GoogleDialerMod#31]
1. The root app works well and can automatically start recording in most time, but when hang up the call without manually click the stop record button, there is nothing saved.

It's this the normal condition?

2. By the way it's this app's root access needs always allowed? By reading the readme, I think it's just change some files and the allow the app get root access once is ok.

**Comment by jacopotediosi** [comment]
Thanks for your reporting.<br><br>

1)

> The root app works well and can automatically start recording in most time, but when hang up the call without manually click the stop record button, there is nothing saved.
> 
> It's this the normal condition?

GoogleDialerMod cannot modify Google Dialer source codes.
Its purpose is only to enable hidden features.
If the call recording button appears, GoogleDialerMod is doing its job.

To report Google Dialer bugs, such as the one reported in this issue, please contact Google.<br><br>

2.

> 
> By the way it's this app's root access needs always allowed? By reading the readme, I think it's just change some files and the allow the app get root access once is ok.

Yes, root access is required for GoogleDialerMod to work
