### ISSUE TITLE
Unable to record audio

### ISSUE THREAD

**Issue by hasan11222** [jacopotediosi/GoogleDialerMod#32]
I am using LOS 17 .
it show me error of   " unable to retrieve audio record pointer for framecount "
And the file it creat has 0 KB
I use 1.15 version 
![Screenshot_20220714-220304_Trebuchet](https://user-images.githubusercontent.com/109313556/179078812-5a335013-5cad-4f79-8869-2569a3b0226d.png)

**Comment by jacopotediosi** [comment]
Your error is about BCR: https://github.com/chenxiaolong/BCR
Open an issue there.
