### ISSUE TITLE
Not working.

### ISSUE THREAD

**Issue by Mineplayerminer** [jacopotediosi/GoogleDialerMod#34]
I'm on the MIUI 12.5.5QJOEUXM. I tried both App and Magisk module. None of them worked for me. Redmi Note 9.

**Comment by jacopotediosi** [comment]
> None of them worked for me
Please describe how it isn't working (e.g., error messages you get, application unexpected behaviours, etc)

https://www.chiark.greenend.org.uk/~sgtatham/bugs.html#respect

**Comment by jacopotediosi** [comment]
BTW, on MIUI Google Dialer is not installed by default. Have you tried to [convert it to a system application](https://www.isunshare.com/android/2-ways-to-convert-user-app-to-system-app.html)?

**Comment by Mineplayerminer** [comment]
On mine it is a default app as it says "com.google.android.dialer" instead of "com.android.dialer" or "phone." I backed up everything and tried uninstalling it. It showed me a default AOSP dialer. Is there any way to fix that?
