### ISSUE TITLE
Call screening

### ISSUE THREAD

**Issue by eusebiomarquesbenitez** [jacopotediosi/GoogleDialerMod#35]
In Xiaomi miui 13 only work when i enable G__speak_easy_enabled and G__speak_easy_bypass_locale_check

/data/data/com.google.android.dialer/shared_prefs/dialer_phenotype_flags.xml

`
<boolean name="G__speak_easy_bypass_locale_check" value="true"/>
`
`
<boolean name="G__speak_easy_enabled" value="true"/>
`

Please enable in default config
thanks.

**Comment by jacopotediosi** [comment]
`G__speak_easy_bypass_locale_check `and `G__speak_easy_enabled` are related to Call Screening, not to Call Recording feature.

**Comment by jacopotediosi** [comment]
For call screen and hold for me features, please refer to issue #7. Closing here.
