### ISSUE TITLE
Call record announcement restored by Dialer

### ISSUE THREAD

**Issue by siavash79** [jacopotediosi/GoogleDialerMod#38]
Hi

I've been using this great app for the past year and it's really useful to me.

However, I've spotted that since the past few days, Google dialer reverts the call record announcement flag once I make a phone call 

Using version 1.03 with Google dialer version 90.0.477356402

**Comment by Rossano95** [comment]
I am having the same problem with the same version

**Comment by jacopotediosi** [comment]
It may be that it was a problem with some specific versions of Google Dialer.

However, just to be sure, the bc27bd20554f78c441fda1a3c8cbda0f0df687d5 commit should prevent in the future the Google Dialer from overwriting the announcement files after applying the mod.

Please wait for version 1.0.5 to be released in the next few days.

If the problem occurs again with that version as well, please reply to this issue and I will be happy to reopen it to investigate deeper.

**Comment by jacopotediosi** [comment]
FYI, version 1.0.5 just released: https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.05
