### ISSUE TITLE
Neither version appears to do anything

### ISSUE THREAD

**Issue by MikeBishop** [jacopotediosi/GoogleDialerMod#4]
I've tried both the app and the Magisk module. The app appears to reset the switches upon exiting and re-entering. The module gives me the prompts during installation, but has no apparent effect. Any suggestions or logs that would be useful?

OP8 running Android 11

**Comment by jacopotediosi** [comment]
Hi, thanks for your report.

This bug should have been fixed by [version 1.04](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.04), which now also works on Android >= 11.

If the problem persists also with that version, please let me know and I will reopen this issue.
