### ISSUE TITLE
Failed to disable "registration has started / ended" sounds on android 13

### ISSUE THREAD

**Issue by koolwiki** [jacopotediosi/GoogleDialerMod#40]
I have upgraded my pixel 4XL to android 13. But I couldn't disable the "registration has started / ended" sounds anymore. I have tried both GoogleDialerMod and GoogleDialerMod-Magisk, didn't work both. Could you please fix this problem? Thank you.

**Comment by jacopotediosi** [comment]
Thanks for the reporting.

It should be fixed with efc58d5d5cdc60d4d6b32e656c5f3fb1e2330224.

Please try [Release v1.04](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.04) and reopen this issue if the bug persists.

**Comment by koolwiki** [comment]
It works now. Thank you!
