### ISSUE TITLE
Call Screen not working in unsupported countries

### ISSUE THREAD

**Issue by Yoanndp** [jacopotediosi/GoogleDialerMod#42]
Hello, I have activated the switches that allow me to use call screening, and it works. However, the call assistant speaks English to my contacts. Is there any way to change the language ?

**Comment by jacopotediosi** [comment]
Hi @Yoanndp, you are probably looking for `enable_call_screen_i18n_tidepods`.
Anyway, I'm still testing and I need a little more time. I hope in the next few days to release an update of GoogleDialerMod to enable all the necessary switches for Call Screen, Hold for Me and Direct my Call.
I'll comment and close this issue when it will be published.

**Comment by jacopotediosi** [comment]
Please try the just released [1.05 version](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.05), which allows to enable the Call Screen feature directly from the Suggested Mods tab.

If you encounter the same problem with that version as well, just leave a comment and I will reopen this issue.

**Comment by Yoanndp** [comment]
Hello, I have activated the Suggested Mod switch, and it seems to change the layout of these settings. However, it doesn't seem to work at all. When someone calls me, I can only answer or decline.

**Comment by jacopotediosi** [comment]
Hi @Yoanndp, the "call screen" button should always appears, not only for spam calls.

Have you tried to close and restart the Dialer a couple of times?

If the problem persists, it can be useful if you provide your logcat, captured while receiving a call, after having the Dialer started in debug mode from adb with the `adb shell -c am start -D com.google.android.dialer` command.

**Comment by Yoanndp** [comment]
Hi, yes I tried to restart it several times. Also, I noticed that the Voice menu is grayed out in the settings, which means I can't configure the voice type (male or female). I have two phone numbers, so I'll try to get some logs when I'll be back from the office.

**Comment by Yoanndp** [comment]
[com.google.android.dialer_logs.log](https://github.com/jacopotediosi/GoogleDialerMod/files/10083103/com.google.android.dialer_logs.log)

**Comment by jacopotediosi** [comment]
Uhm, something weird is going on.

It is not normal that the Voice menu is grayed out and in your logcat I see that your Call Screen is using the US language instead of FR.

I have the following questions for you:
- Are you French? (which is your phone locale?)
- Which version of Google Dialer are you using?
- Can you try if enabling the `G__speak_easy_use_soda_asr` switch something changes (i.e. the Voice menù unlocks)?

**Comment by Yoanndp** [comment]
• My phone language is set to French
• version 94.0.48803600-pixel2022
• It doesn't change anything
![Screenshot_20221124-111715_cropped](https://user-images.githubusercontent.com/13591243/203759179-5131b5d2-fcf6-48e2-85cc-10fe26dbab7a.png)

**Comment by jacopotediosi** [comment]
Could you please send me a logcat also of when you open the Filtrage d'appels screen in the Dialer settings?

**Comment by Yoanndp** [comment]
[Call Screening settings.log](https://github.com/jacopotediosi/GoogleDialerMod/files/10083568/Call.Screening.settings.log)

**Comment by Yoanndp** [comment]
Did you find something relevant ?

**Comment by jacopotediosi** [comment]
Not yet. In the meantime, do you have already tried to remove all the applied mods (using the trash icon at the top right in GoogleDialerMod, it could hangs for some minutes because of a known performance problem which I will solve in future releases), force close the Dialer, delete its data (not just the cache) and try again by activating only the suggested call screen mod?

**Comment by jacopotediosi** [comment]
It seems to be a language pack problem, but I don't understand why your Dialer downloaded the US one and not the FR one.
Even setting up my Android emulator in French, connecting to a French VPN, and simulating a French carrier, I can't replicate your bug.
This is why I am suggesting you to clear all Dialer data and start over.

**Comment by jacopotediosi** [comment]
Eventually I can separate the call screen feature into two buttons, one that enables the traditional call screen and one that adds the advanced autofilter that doesn't seem to work for you

**Comment by Yoanndp** [comment]
> Not yet. In the meantime, do you have already tried to remove all the applied mods (using the trash icon at the top right in GoogleDialerMod, it could hangs for some minutes because of a known performance problem which I will solve in future releases), force close the Dialer, delete its data (not just the cache) and try again by activating only the suggested call screen mod?

I have done what you said and it didn't worked.
1. Click on the Trash icon from GDMod
2. Force close the Dialer app 
3. Delete all data 
4. Activated only the call screening mod
5. Force close and clear cache several times

It got the same menu as before, and still grayed voice menu.

> Eventually I can split the "enable call screen" feature into two buttons, one that enables just the traditional call screen and one that adds also the advanced automatic filter that doesn't seem to work for you. So you can at least use the basic call screen.

Yeah, it may worth a try ! If you are about to implement that function, I can be your beta tester.

**Comment by Yoanndp** [comment]
> It seems to be a language pack problem, but I don't understand why your Dialer downloaded the US one and not the FR one.
> Even setting up my Android emulator in French, connecting to a French VPN, and simulating a French carrier, I can't replicate your bug.
> This is why I am suggesting you to clear all Dialer data and start over.

Oh I see you're mentioning "French VPN" and "French Carrier". I'm located in Belgium, it could help you in your research

**Comment by jacopotediosi** [comment]
> Oh I see you're mentioning "French VPN" and "French Carrier". I'm located in Belgium, it could help you in your research

Founded! https://support.google.com/phoneapp/answer/9118387?hl=en
Probably Google Dialer detect your SIM is not of one of their supported countries. I need to investigate on that.

**Comment by Yoanndp** [comment]
> > Oh I see you're mentioning "French VPN" and "French Carrier". I'm located in Belgium, it could help you in your research
> 
> Founded! https://support.google.com/phoneapp/answer/9118387?hl=en
> Probably Google Dialer detect your SIM is not of one of their supported countries. I need to investigate on that.

Yeah that's what I see on this website. I hope you will be able to find a way to spoof the SIM card. Thank you for your help ! I think we can close this thread while you're investigating. Feel free to reopen anytime if needed.

**Comment by jacopotediosi** [comment]
Useful logs captured:

```
Starting download: https://storage.googleapis.com/dialer-cs-tts/manifest-configs/v202110040940.pb
Is http uri, downloading (uri: https://storage.googleapis.com/dialer-cs-tts/manifest-configs/v202110040940.pb)
com.android.dialer.callscreen.impl.flags.Flags.modelForLanguage:131 simCountry be is not supported
com.android.dialer.callscreen.impl.flags.Flags.getSupportedLanguage:203 simCountry be is not supported
com.android.dialer.callscreen.impl.flags.Flags.modelForLanguage:131 simCountry be is not supported
com.android.dialer.callscreen.impl.mdd.ManifestConfigOverrider.lambda$override$0:67 languageCode fr-BE is not supported
```

**Comment by jacopotediosi** [comment]
Ok, I understand the issue here. Actually it is a limitation imposed by the Google Dialer to prevent Call Screen from being activated outside of some countries.

The language set on the phone does not matter. The language of the voice messages depends on the carrier of the SIM inserted in the phone.
You are using a Belgian sim, so Google Dialer tries to download the fr-BE languagepack (which doesn't exist) instead of the fr-FR one.

There are many possibilities for developing a workaround, e.g. spoof the properties obtained by Google Dialer. The same problem seems to be the reason why the Hold for Me feature does not activate as well, so we can make that work too.

Meanwhile, @Yoanndp, if you want to make it work, open a shell with the `adb shell`, then type:
```
su
setprop gsm.sim.operator.iso-country fr
setprop gsm.operator.iso-country fr
```

Please update me if it works for you.

If it causes you any problems, you can rollback with the commands:
```
su
setprop gsm.sim.operator.iso-country be
setprop gsm.operator.iso-country be
```

**Comment by Yoanndp** [comment]
> Ok, I understand the issue here. Actually it is a limitation imposed by the Google Dialer to prevent Call Screen from being activated outside of some countries.
> 
> The language set on the phone does not matter. The language of the voice messages depends on the carrier of the SIM inserted in the phone.
> You are using a Belgian sim, so Google Dialer tries to download the fr-BE languagepack (which doesn't exist) instead of the fr-FR one.
> 
> There are many possibilities for developing a workaround, e.g. spoof the properties obtained by Google Dialer. The same problem seems to be the reason why the Hold for Me feature does not activate as well, so we can make that work too.
> 
> Meanwhile, @Yoanndp, if you want to make it work, open a shell with the `adb shell`, then type:
> ```
> su
> setprop gsm.sim.operator.iso-country fr
> ```
> 
> Please update me if it works for you.
> 
> Also, please note that the Call Screen feature works only if the caller number is from your same SIM Country. E.g., if you use the above commands to spoof your SIM Country as a FR one, the Call Screen button won't appear when an Italian number (starting with +39) calls you.

Smart ! I'll apply those command but could it break something? Like fucking up the network or anything sim related ?

**Comment by Yoanndp** [comment]
> Also, please note that the Call Screen feature works only if the caller number is from your same SIM Country. E.g., if you use the above commands to spoof your SIM Country as a FR one, the Call Screen button won't appear when an Italian number (starting with +39) calls you.

Well, as I have a Belgian SIM card, and most of my contacts are Belgian people (with Belgian number +32), I guess it makes not sense to spoof the SIM Card

**Comment by jacopotediosi** [comment]
> Smart ! I'll apply those command but could it break something? Like fucking up the network or anything sim related ?
Nah, this workaround doesn't resist reboot either.

**Comment by Yoanndp** [comment]
By changing the boot properties from Be to Fr, I was able to handle a phone call (from a Belgian number) to my own number and the assistant spoke in French. However, after a reboot, the feature disappeared (I guess because of the non-persistent flag). Would creating a Magisk module help?

**Comment by jacopotediosi** [comment]
> Would creating a Magisk module help?

Nope. I'm creating an ad-hoc GoogleDialerMod patch without Magisk. Stay tuned, because we will also have the possibility to modify all the audio messages and add custom buttons in the Call Screen.

Meanwhile, consider the setprop method as a temporary workaround, but it won't survive reboots.

**Comment by Yoanndp** [comment]
Thank you for help, I remain available if needed

**Comment by jacopotediosi** [comment]
Thank you for having tested that call from a belgian number. It was helpful to better understand!

**Comment by jacopotediosi** [comment]
Hi @Yoanndp,
Version [1.06](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.06) should enable the Call Screen feature even for unsupported countries. The wifi activation screen still takes a few seconds but then it should works.

If you encounter any problems, since you come from a previous version, I suggest as usual to use the GoogleDialerMod trash icon, delete the Dialer data, and then start over.

Notice also there may be a few seconds hang when you choose the language after enabling the switch, but the app is working and you just have to wait. In general, I will soon have to fix the performance of the application.

Please give it a try and keep me updated 😄

**Comment by Rossano95** [comment]
Hi, version 1.05 works for me. With version 1.06 when I select the italian language the google dialer mod app crashes. Just downgraded for now. Thank you for your work.

**Comment by jacopotediosi** [comment]
> Hi, version 1.05 works for me. With version 1.06 when I select the italian language the google dialer mod app crashes. Just downgraded for now. Thank you for your work.

Uhm compiling the apk in release mode broke something.

**Comment by Yoanndp** [comment]
> Hi @Yoanndp,
> Version [1.06](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.06) should enable the Call Screen feature even for unsupported countries. The wifi activation screen still takes a few seconds but then it should work.
> 
> If you encounter any problems, since you come from a previous version, I suggest as usual to use the GoogleDialerMod trash icon, delete the Dialer data, and then start over.
> 
> Notice also there may be a few seconds hang when you choose the language after enabling the switch, but the app is working and you just have to wait. In general, I will soon have to fix the performance of the application.
> 
> Please give it a try and keep me updated 😄 

The app crashes when selecting language

**Comment by jacopotediosi** [comment]
@Yoanndp @Rossano95 Could you try it again?
I have reuploaded the correct apk always there: https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.06

**Comment by Rossano95** [comment]
Now it works again. Thank you

**Comment by Yoanndp** [comment]
The menu appears but voice is still grayed out and the feature doesn't work when someone calls me. Also, after a reboot, the feature disappeared

**Comment by jacopotediosi** [comment]
> The menu appears but voice is still grayed out and the feature doesn't work when someone calls me. Also, after a reboot, the feature disappeared

It is because you are coming from the previous version. The switch on GoogleDialerMod should be back to off and you should be able to try again.

**Comment by shadyrexman** [comment]
> @Yoanndp @Rossano95 Could you try it again?
> I have reuploaded the correct apk always there: https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.06

Thank you for your great work!

**Comment by shadyrexman** [comment]
In build 1.06 I can use the enhanced Call Screen, but the hold for me still keeps activating though .

**Comment by Yoanndp** [comment]
The hold for me still doesn't work ![Screenshot_20221127-110029.png](https://user-images.githubusercontent.com/13591243/204129405-f72bcd3f-d4be-48fd-9e26-e4033385c7dd.png) Should I enable something?

**Comment by jacopotediosi** [comment]
Hi!
Sorry, but the latest update (v1.06) is just about Call Screen.
Hold for Me is a totally different feature and I'll release a future update to enable it as well. At the moment it is normal that Hold for Me isn't working and you cannot enable it yourself using switches. To be enabled, it requires a totally different method and (for me) to study and reverse engineering the Dialer. Stay tuned, because I'll implement that soon, but please stop talking about that under this ticket because this is just about Call Screen and not about Hold for Me.
Thanks.
I'm closing this issue as the Call Screen implementation is finished and it's reported as working for multiple users.

**Comment by jacopotediosi** [comment]
As a reference, the ticket about Hold for Me is #7.

**Comment by Yoanndp** [comment]
Alright, thank you

**Comment by swx-tr** [comment]
Hi, is it possible to screening an other languages? I need Turkish 😌
