### ISSUE TITLE
Dialer missing CAPTURE_AUDIO_OUTPUT permission (not installed as system app)

### ISSUE THREAD

**Issue by B0j4ngl35** [jacopotediosi/GoogleDialerMod#46]
## Overview
Call Screen feature does not display upon incoming call(s)

## Steps to Reproduce

1.  Rebooted to no avail
2.  Cleared cache and data
3.  Forced stopped app 3 - 4 times

## Expected Behavior
[logreader_2022-12-06_11-40.log.zip](https://github.com/jacopotediosi/GoogleDialerMod/files/10168499/logreader_2022-12-06_11-40.log.zip)

## System Information
- Device and model: OnePlus 8 5G UW

- ROM and Android version: Stock OOS11 

- Google Dialer is installed as a system app

- Magisk 44643ad7-alpha

- Installed GoogleDialerMod version: 1.6

- Installed Google Dialer version: 95.0.491468435-publicbeta

- Your device language (locale): English_US

- Your location USA

**Comment by jacopotediosi** [comment]
`missing permission: android.permission.CAPTURE_AUDIO_OUTPUT`
You didn't install Google Dialer as system app

**Comment by jacopotediosi** [comment]
This is not a GoogleDialerMod bug, but it is a useful suggestion to improve the following things:
- add to the splash screen a check that the dialer is installed as a system app / has the right permissions
- add to the README.MD and XDA thread that installing the dialer as a system app is a requirement for logging to work
- eventually add a new feature to transform the dialer into a system app (it could be complicated to support all android versions and the various device models)
