### ISSUE TITLE
Support GApps other than the Dialer (e.g. "Message Organization" feat in Messages)

### ISSUE THREAD

**Issue by jacopotediosi** [jacopotediosi/GoogleDialerMod#51]
As the title says, it would be useful to mods other Google Apps in addition to the Google Dialer.
The idea is to add an additional tab to the main layout to select which of the supported applications the user intends to patch.

E.g., on Google Messages, we can enable the "Message Organization" and the "Auto-delete OTPs after 24 hrs" features (https://www.makeuseof.com/auto-delete-otp-messages-android/).
For the sake of completeness, I just got it working overriding the following phenotype FlagOverrides (certainly not all of them are necessary, but I don't have time now to do an accurate analysis):
```
adb shell
su
/data/data/com.jacopomii.googledialermod/sqlite3 /data/data/com.google.android.gms/databases/phenotype.db "SELECT DISTINCT name,boolVal FROM FlagOverrides WHERE packageName='com.google.android.apps.messaging#com.google.android.apps.messaging'"
bugle_phenotype__bug_192909536_supersort_classify_missing_messages_only_when_charging|0
bugle_phenotype__conversation_labels_enabled|1
bugle_phenotype__enable_experiment_carrier_config_override|1
bugle_phenotype__enable_otp_auto_deletion|1
bugle_phenotype__enable_phenotype_override|1
bugle_phenotype__enable_smart_action_settings_page|1
bugle_phenotype__enable_starring_suggestion|1
bugle_phenotype__enable_supersort_annotators|1
bugle_phenotype__enable_text_classifier_actions_in_notifications|1
bugle_phenotype__enable_text_classifier_address_message_annotations|1
bugle_phenotype__enable_text_classifier_contact_message_annotations|1
bugle_phenotype__enable_text_classifier_datetime_message_annotations|1
bugle_phenotype__enable_text_classifier_email_message_annotations|1
bugle_phenotype__enable_text_classifier_map_link_message_annotations|1
bugle_phenotype__enable_text_classifier_phone_message_annotations|1
bugle_phenotype__enabled_testopenbeta_feature|1
bugle_phenotype__reranker_enable_type_sorting|1
bugle_phenotype__supersort_badge_all_filter|1
bugle_phenotype__supersort_enable_qpbc|1
bugle_phenotype__supersort_enable_update_donation_banner|1
bugle_phenotype__supersort_use_only_work_manager|0
```

This enhancement would probably require a major refactor of the GoogleDialerMod codebase and maybe a project name change (e.g. to "GAppsMod").

**Comment by jacopotediosi** [comment]
Before doing this it is strongly recommended to reorganize the file structure of the app

**Comment by Yoanndp** [comment]
Hello, for those who want to make these changes directly with a SQL editor, I have created a [script](https://github.com/Yoanndp/generate_sql_queries) that allows you to generate SQL queries via an input file (in "Name | BoolVal" format).

**Comment by jacopotediosi** [comment]
> Hello, for those who want to make these changes directly with a SQL editor, I have created a [script](https://github.com/Yoanndp/generate_sql_queries) that allows you to generate SQL queries via an input file (in "Name | BoolVal" format).

Remember, after changing flags, to force close the Google Messages app and to delete the /data/data/com.google.android.apps.messaging/files/phenotype folder

**Comment by jacopotediosi** [comment]
Multiple GApps support is still in progress, but the "Message Organization" feature of Messages is now supported (168b209).

**Comment by Yoanndp** [comment]
Thanks for the work! If needed, I can test a beta before creating an official release

**Comment by jacopotediosi** [comment]
> Thanks for the work! If needed, I can test a beta before creating an official release

Here's a debug APK compiled from the last commit 168b209: [app-debug.zip](https://github.com/jacopotediosi/GoogleDialerMod/files/11276611/app-debug.zip)

**Comment by jacopotediosi** [comment]
I intend to wait to support multiple apps even in the Boolean Mods tab before publishing a release

**Comment by jacopotediosi** [comment]
Implemented with 8433bda. I'll publish a release version soon. Meanwhile, here is the current debug apk: [8433bda.zip](https://github.com/jacopotediosi/GoogleDialerMod/files/11402061/8433bda.zip).

https://user-images.githubusercontent.com/20026524/236343798-8fae4255-5727-4df0-94c7-eeac475c7e73.mp4

**Comment by UltraHQ** [comment]
Hi, sorry, but I just wanted to say thank you!

Finally, someone is breaking that "US only" habbit from Google.
Thanks, for making our pixels what it should be, for unlocking the features we initially paid for.

**Comment by jacopotediosi** [comment]
> Hi, sorry, but I just wanted to say thank you!
> 
> Finally, someone is breaking that "US only" habbit from Google. Thanks, for making our pixels what it should be, for unlocking the features we initially paid for.

Thanks, I'm trying my best. I plan to create suggested mods for more and more GApps over time. The next ones will probably be the play store and android auto. Feel free to suggest which features you would like, for example by sending screenshots or articles from the 9to5 website showing which hidden features can be unlocked.

**Comment by Yoanndp** [comment]
Do you think it is possible to enable 5G in countries where it is not supported? For example, here in Belgium we have 5G relays and the phone supports 5G, but it is impossible to connect to the 5G network from a Pixel 7. I'm not sure if these settings are in the db phenotype.

**Comment by jacopotediosi** [comment]
> Do you think it is possible to enable 5G in countries where it is not supported? For example, here in Belgium we have 5G relays and the phone supports 5G, but it is impossible to connect to the 5G network from a Pixel 7. I'm not sure if these settings are in the db phenotype.

Are you sure you are using the correct APN?

**Comment by Yoanndp** [comment]
Yes, this is a known problem here in Belgium. Nobody can connect to the 5G network using their Pixel's phone.
