### ISSUE TITLE
Enable call recording before pick up

### ISSUE THREAD

**Issue by Taknok** [jacopotediosi/GoogleDialerMod#58]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
When calling someone, there is a short moment before the person picks up. During this time, various icon are greyed and cannot be activated, included the call recording feature.
![Screenshot_20230213-114043](https://user-images.githubusercontent.com/12498020/218437968-050562fb-9898-4b9f-9ef3-28c33a567ffe.jpg)

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )
The call recording button can be activated and the recording would start right from the start, recording the "rings".

I do not know if there is a setting in the phenotypes.db allowing this or if it requires a patch of the apk (which would be out of this project scope).

Regardless : thank you for this useful project !

**Comment by jacopotediosi** [comment]
Regarding this issue, looking to the dialer source code, it seems not possible to do without patching the apk. Sorry :(
