### ISSUE TITLE
Call screening: Receiver can't hear Google's voice

### ISSUE THREAD

**Issue by Ashesh3** [jacopotediosi/GoogleDialerMod#61]
## Overview
When using call screening feature on my Android phone, the receiver can't hear Google's voice. I do have the options to activate it and it has downloaded all the files (over WiFi). The transcript works but the receiver can't hear Google's voice.

## Steps to Reproduce
1. Make a call using another number to your phone.
2. When the call is connected, tap on the "Screen call" option.
3. Wait for Google's voice to speak. The receiver will hear nothing but the transcript is shown (What google is going to speak).

## Expected Behavior
The receiver should be able to hear Google's voice and instructions clearly during the call screening process.

## Actual Behavior
The receiver cannot hear Google's voice during the call screening process.

## Screenshots
![image](https://user-images.githubusercontent.com/3626859/224628829-42d74032-7c08-4644-a457-b609e2758dc9.png)

## System Information
- Device and model: Redmi note 10 Pro Max (sweetin)

- ROM and Android version: ArrowOS , Android 11

- Is Google Dialer installed as system app: Yes

- Installed Magisk / other SU Manager version: Magisk

- Installed GoogleDialerMod version:
```
    versionCode=106 minSdk=21 targetSdk=33
    versionName=1.06
    signatures=PackageSignatures{f5d92d1 version:2, signatures:[8c539576], past signatures:[]}
```

- Installed Google Dialer version:
```
    versionCode=11348648 minSdk=24 targetSdk=33
    versionName=100.0.512999549-publicbeta
    signatures=PackageSignatures{4c5c7 version:3, signatures:[788396df], past signatures:[]}
    versionCode=6702824 minSdk=24 targetSdk=30
    versionName=58.0.354390404
    signatures=PackageSignatures{dcd2192 version:0, signatures:[], past signatures:[]}
```

- Your device language (locale):
```
[persist.sys.locale]: [en-US]
[ro.product.locale]: [en-US]
```

- Your location (country of the SIM and country where you are):
```
[gsm.operator.iso-country]: [in,]
[gsm.sim.operator.iso-country]: [in]
```

## Logcat
[logs.txt](https://github.com/jacopotediosi/GoogleDialerMod/files/10954468/logs.txt)

**Comment by jacopotediosi** [comment]
The receiver is not supposed to hear Google's voice.
If you meant the caller, instead, there is already another open issue: #47.

**Comment by Ashesh3** [comment]
I did mean the caller, the other person on the call.
