### ISSUE TITLE
Dialer is not installed. 

### ISSUE THREAD

**Issue by Dreamail** [jacopotediosi/GoogleDialerMod#63]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )

Open dialer mod and noticed me I didn't install Google dialer, but I have installed it and it's public beta version. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Open mod 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Screenshots
[NOTE]: # ( If applicable, add screenshots to help explain your problem. )
![Screenshot_20230320-172407_Settings.png](https://user-images.githubusercontent.com/46253320/226297915-ec7eca69-c505-432d-9cbe-641533ede31c.png)

## System Information
- Device and model: 
OnePlus 9rt
- ROM and Android version: 
Pixel Experience android 13
- Is Google Dialer installed as system app: 
Preinstall by rom 
- Installed Magisk / other SU Manager version: 
KernelSU
[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.jacopomii.googledialermod | grep version"` command )
- Installed GoogleDialerMod version:
    versionCode=106 minSdk=21 targetSdk=33
    versionName=1.06
    signatures=PackageSignatures{302b64e version:2, signatures:[8c539576], past signatures:[]}

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.google.android.dialer | grep version"` command )
- Installed Google Dialer version:

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep locale"` command )
- Your device language (locale):
[persist.sys.locale]: [en-US]
[ro.product.locale]: [en-US]

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep iso-country"` command )
- Your location (country of the SIM and country where you are):
[gsm.operator.iso-country]: [cn,cn]
[gsm.sim.operator.iso-country]: [cn,cn]

## Logcat
[NOTE]: # ( 
Launch the Dialer in Debug mode using the `adb shell "am start -D com.google.android.dialer"` command.
Open another terminal and use the `adb logcat > logs.txt` command to start capturing logs.
Perform the necessary steps to replicate the bug, then press CTRL+C to stop capturing logs.
Attach below the resulting logs.txt file.
)

**Comment by jacopotediosi** [comment]
Wait till I'll compile the actual github version, which uses a new root method which should be compatible with kernelSU

**Comment by Dreamail** [comment]
waiting for

**Comment by jacopotediosi** [comment]
@Dreamail can you please check again with the just released [GoogleDialerMod v2.00](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v2.00) ?
Thanks!

**Comment by jacopotediosi** [comment]
If the error keeps appearing, it's probably because KernelSU doesn't allow apps to launch su shells with global namespaces: https://kernelsu.org/guide/faq.html#is-there-any-mount-master-global-mount-namespace-in-kernelsu

In that case, probably GoogleDialerMod isn't the only app affected and I suggest you to migrate to a better root environment (e.g. Magisk).

**Comment by Dreamail** [comment]
![Screenshot_20230322-123310_GoogleDialerMod.png](https://user-images.githubusercontent.com/46253320/226802986-8d63d2f3-c028-4166-8e75-44ac4ad5d16c.png)
