### ISSUE TITLE
Call recording failed (Dialer not installed as system app)

### ISSUE THREAD

**Issue by PomyloneKodowanie** [jacopotediosi/GoogleDialerMod#65]
Please lat me know what data can I provide, i am running 19.1 lineage os with magisk and recording optons appeared in dialer APP but i cant find the way to play it nor the WAV file from regular (non-su) file explorer

**Comment by jacopotediosi** [comment]
Recordings are supposed to be played directly from the calling history in the Dialer app

**Comment by PomyloneKodowanie** [comment]
> Recordings are supposed to be played directly from the calling history in the Dialer app

Yes I understand this much, the icon is not showing up https://photos.app.goo.gl/6vk9trnC44DqDgGg9

**Comment by jacopotediosi** [comment]
When you end a recording, you get a "registration failed" toast message or a "registration saved" one?

**Comment by PomyloneKodowanie** [comment]
I believe neither, (it's late and I am ready to sleep) I usually don't miss such thing.

**Comment by PomyloneKodowanie** [comment]
and no taster on this one https://youtu.be/uSrsGy6tIbg?t=47

**Comment by jacopotediosi** [comment]
Can you check if your Google Dialer is installed as system app?
Also, the "silence call recording alerts" mod is off in your GoogleDialerMod?

**Comment by PomyloneKodowanie** [comment]
Sorry I am on hiatus with root on the phone, i downloaded something and it lagged the hell oout of my phone, sucks not to have call recroding though

**Comment by jacopotediosi** [comment]
> Can you check if your Google Dialer is installed as system app? Also, the "silence call recording alerts" mod is off in your GoogleDialerMod?

@PomyloneKodowanie to triage your bug, I need you to answer my above questions ^

**Comment by PomyloneKodowanie** [comment]
Silence csll is grayed out since it checks for version i assume , system app i dont know IF i know how to check it, i'll look for it i guess

**Comment by PomyloneKodowanie** [comment]
It's not a system App then, lineage comes with different dialer and it wasn't in openGapps.

Awsiting further instructions

**Comment by jacopotediosi** [comment]
You need to install Dialer as system app, otherwise it doesn't have permissions to record.
If you google "android convert app to system" there are numerous tutorials.

Sidenote: it is already planned to add an alert in GoogleDialerMod that warns of the lack of permissions by the Dialer (#46).

**Comment by PomyloneKodowanie** [comment]
I'll reopen for posterity, I've installed as system app and even downgraded to version 93, it doesn't record, it however displayed toaster that this device is not supported and the app might not work (it does make calls), 93x shows warnining in call recording menu - not avaialable in your location.
Hope it won't offend you, in the end I went with Automatic call recorder from G Play store (https://play.google.com/store/apps/details?id=com.appstar.callrecorder&hl=en_US) and it seems to work

**Comment by jacopotediosi** [comment]
No logcat provided by the OP, who also skipped the bug reporting template. It is noteworthy that call recording feature is reported as working by multiple users. Also, OP didn't follow README instructions about clearing dialer data and restarting twice, which is why they got "device not supported" and "recording not available in your location" error messages.

Initially, Google Dialer was not installed as a system app. About that, GoogleDialerMod will show a warning in future releases (commit already set up on my local git).

Eventually, further issue about call recording failures will be discussed on the already existing ticket #22.
