### ISSUE TITLE
Will mute recording alert again 

### ISSUE THREAD

**Issue by OmarRol-1** [jacopotediosi/GoogleDialerMod#67]
There is a possibility of having Silence call recording alerts again

**Comment by jacopotediosi** [comment]
No, at least not with this project. Google patched the Dialer and it currently rewrites the announcement audio files at the start of each recording.
It might still be possible to mute those audios by patching the Dialer apk or hooking with Xposed, but this project is just about applying mods via the filesystem or via phenotypedb.
