### ISSUE TITLE
Call record lost after reboot 

### ISSUE THREAD

**Issue by bggold** [jacopotediosi/GoogleDialerMod#70]
On version 104.0.525326234-publicbeta-pixel2022 after a reboot call record has to be applied again. I have force closed the app several times and waited.  Still does not show up.

Reboot phone

Should survive reboot

Call record lost 

- Device and model: pixel 7 pro

- ROM and Android version:  13

- Installed Magisk / other SU Manager version:  26.1

Thanks

**Comment by jacopotediosi** [comment]
After reboot, the call recording switch in suggested mods tab is still turned on?

**Comment by bggold** [comment]
No it is not.

**Comment by bggold** [comment]
I just had to reboot again and after I checked and the switch was on and after force closing the phone app a few times it's working.  You can close this issue.  If it happens again I will gather you all the logs.

Thanks

**Comment by jacopotediosi** [comment]
Thanks for your feedback. Probably there was an error applying the mod the first time or there was a delay by the Dialer acquiring the flags from the phenotypedb.
Whatever happened, I think the new update I'm preparing (current commit, apk unreleased yet) should solve it, as I changed the way the application interacts with the phenotypedb (it doesn't use shell wrappers anymore and sqlite is implemented directly via java libraries).
