### ISSUE TITLE
Phone: Videocall (ViLTE) not working

### ISSUE THREAD

**Issue by Kuartzz** [jacopotediosi/GoogleDialerMod#74]
## Overview
[NOTE]: # ( Give a BRIEF summary about your problem )
Trying to enable videocalls

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1.  Enable videocall flags
2.  Call

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Videocall

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Cant videocall

## Screenshots
[NOTE]: # ( If applicable, add screenshots to help explain your problem. )

## System Information
- Device and model: Pixel 6a

- ROM and Android version: Android 14 UPB2.230407.014.A1

- Is Google Dialer installed as system app: Yes

- Installed Magisk / other SU Manager version: Magisk

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.jacopomii.googledialermod | grep version"` command )
- Installed GoogleDialerMod version:
    versionCode=300 minSdk=21 targetSdk=33
    versionName=3.00
    signatures=PackageSignatures{50a1e92 version:2, signatures:[8c539576], past signatures:[]}

[NOTE]: # ( Paste below the output of the `adb shell "dumpsys package com.google.android.dialer | grep version"` command )
- Installed Google Dialer version:
    versionCode=11851588 minSdk=24 targetSdk=33
    versionName=105.0.529096231-publicbeta
    signatures=PackageSignatures{45e4e98 version:3, signatures:[788396df], past signatures:[]}
    versionCode=11348628 minSdk=24 targetSdk=33
    versionName=100.0.512999549
    signatures=PackageSignatures{fa15957 version:0, signatures:[], past signatures:[]}

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep locale"` command )
- Your device language (locale):
[persist.sys.locale]: [es-ES]
[ro.product.locale]: [en-US]

[NOTE]: # ( Paste below the output of the `adb shell "getprop | grep iso-country"` command )
- Your location (country of the SIM and country where you are):
[gsm.operator.iso-country]: [es]
[gsm.sim.operator.iso-country]: [es]

## Logcat
[NOTE]: # ( 
Launch the Dialer in Debug mode using the `adb shell "am start -D com.google.android.dialer"` command.
Open another terminal and use the `adb logcat > logs.txt` command to start capturing logs.
Perform the necessary steps to replicate the bug, then press CTRL+C to stop capturing logs.
Attach below the resulting logs.txt file.
)
[logs.txt](https://github.com/jacopotediosi/GoogleDialerMod/files/11472293/logs.txt)

**Comment by jacopotediosi** [comment]
Relevant logcat lines:
```
05-14 17:37:00.641  7389  7419 I DialerVideoCallIntroController: com.android.dialer.videocallintro.dataservice.impl.VideoCallIntroController.lambda$getVideoCallingTech$0:62 Duo is supported: true, ViLTE is supported: false
05-14 17:37:12.669  7389  7415 I DialerVideoCallSettingsIntegration: com.android.dialer.videocall.settings.impl.multibinding.VideoCallSettingsIntegration.lambda$getPrefData$0:93 Phone Account supports Carrier Video Calling.
05-14 17:37:20.740  7389  7416 I DialerCallUtil: com.android.dialer.util.call.CallUtil.isVideoEnabled:143 isVideoEnabled: false
05-14 17:37:20.740  7389  7419 I DialerDuoKitImpl: com.android.dialer.duo.impl.DuoKitImpl.systemSupportsDuoUpgrade:560 Supported: true
05-14 17:37:20.741  7389  7419 I DialerCallUtil: com.android.dialer.util.call.CallUtil.getVideoCallingAvailability:94 disallow RTT to Videocall transition due to flag
05-14 17:37:20.741  7389  7419 I DialerRttConfigurationCacheImpl: com.android.dialer.rtt.settings.impl.configuration.RttConfigurationCacheImpl.getCachedRttConfiguration:68 successfully fetched rtt configuration: UNSUPPORTED
05-14 17:37:22.706  7389  7437 I DialerVideoTypePickerImpl: com.android.dialer.videotypepicker.impl.VideoTypePickerImpl.lambda$isPhoneAccountVilteCapableAndNoPreferredVideoType$4:237 isDefaultTypeUnspecified = false, isPhoneAccountVilteCapable = false
```

I'm not entirely sure, but it seems to me that your phone or carrier don't support Video over LTE (ViLTE). Probably if you install Duo/Meet the video call button will try to start a Meet call for the contacts who use it, which is still an alternative to native video calls.
