### ISSUE TITLE
Call recording ad silenceWill they be back?

### ISSUE THREAD

**Issue by OmarRol-1** [jacopotediosi/GoogleDialerMod#77]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

## Alternatives
[NOTE]: # ( A clear and concise description of any alternative solutions or features you've considered )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by jacopotediosi** [comment]
@OmarRol-1, you already had a reply in #67.
Please stop wasting my time.
Thanks.
