### ISSUE TITLE
Not functioning.

### ISSUE THREAD

**Issue by Samg381** [jacopotediosi/GoogleDialerMod#9]
Google Pixel 4XL, dialer beta. Android 11 RQ3A.201605.005.
Tried both root and magisk versions, no dice.

**Comment by jacopotediosi** [comment]
Thanks for the reporting.

It should be fixed with efc58d5d5cdc60d4d6b32e656c5f3fb1e2330224.

Please try [Release v1.04](https://github.com/jacopotediosi/GoogleDialerMod/releases/tag/v1.04) and reopen this issue if the bug persists.
